apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: argocd
      goldilocks.fairwinds.com/enabled: "true"
    name: argocd
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: default
      goldilocks.fairwinds.com/enabled: "true"
    name: default
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      kubernetes.io/metadata.name: elasticsearch
      goldilocks.fairwinds.com/enabled: "true"
    name: elasticsearch
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      kubernetes.io/metadata.name: external-secrets
      goldilocks.fairwinds.com/enabled: "true"
    name: external-secrets
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      kubernetes.io/metadata.name: goldilocks
      goldilocks.fairwinds.com/enabled: "true"
    name: goldilocks
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      kubernetes.io/metadata.name: kibana
      goldilocks.fairwinds.com/enabled: "true"
    name: kibana
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      kubernetes.io/metadata.name: vault
      goldilocks.fairwinds.com/enabled: "true"
    name: vault
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
    labels:
      kubernetes.io/metadata.name: fluent-bit
      goldilocks.fairwinds.com/enabled: "true"      
    name: fluent-bit
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
    
