apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: argocd
    labels:
      kubernetes.io/metadata.name: argocd
- apiVersion: v1
  kind: Namespace
  metadata:
    name: default
    labels:
      kubernetes.io/metadata.name: default
- apiVersion: v1
  kind: Namespace
  metadata:
    name: elasticsearch
    labels:
      kubernetes.io/metadata.name: elasticsearch
- apiVersion: v1
  kind: Namespace
  metadata:
    name: external-secrets
    labels:
      kubernetes.io/metadata.name: external-secrets
- apiVersion: v1
  kind: Namespace
  metadata:
    name: kibana
    labels:
      kubernetes.io/metadata.name: kibana
- apiVersion: v1
  kind: Namespace
  metadata:
    name: vault
    labels:
      kubernetes.io/metadata.name: vault
- apiVersion: v1
  kind: Namespace
  metadata:
    name: fluent-bit
    labels:
      kubernetes.io/metadata.name: fluent-bit